version: "3"

services:
  whoogle-search:
    image: benbusby/whoogle-search
    container_name: whoogle-search
    #environment: # Uncomment to configure environment variables
      # Basic auth configuration, uncomment to enable
      #- WHOOGLE_USER=<auth username>
      #- WHOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- WHOOGLE_PROXY_USER=<proxy username>
      #- WHOOGLE_PROXY_PASS=<proxy password>
      #- WHOOGLE_PROXY_TYPE=<proxy type (http|socks4|socks5)
      #- WHOOGLE_PROXY_LOC=<proxy host/ip>
    ports:
      - 5000:5000
    restart: unless-stopped
run:
  - exec:
     cmd:
       - "mkdir -p /shared/ssl/"
  - replace:
     filename: "/etc/nginx/conf.d/discourse.conf"
     from: /server.+{/
     to: |
       server {
         listen 80;
         return 301 https://$$ENV_DISCOURSE_HOSTNAME$request_uri;
       }
       server {
  - replace:
     hook: ssl
     filename: "/etc/nginx/conf.d/discourse.conf"
     from: /listen 80;\s+gzip on;/m
     to: |
       listen 443 ssl http2;
       ssl_protocols TLSv1.2 TLSv1.3;
